# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e7c51e497e889a4dbfb57fbf3aae4d22f41c4177df60dbd3e0d7c0992ebea334d2ed5a305e6224e97f1901d556603d6368eb6a5b1d65a5537c855230c9e5701

test:
  secret_key_base: 39286cb692c815ca8f481ead13627184cd7c305526e83d01c210b7d1b385a8478e68fc4e01d6529e6313294bf53d158c5bcb95bc3c9227b6e3ca1abb83961036

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
